In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
az=np.zeros((2,2))
ar=np.random.random((5,3))
ae= np.arange(0,6,1)
log=np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]))
newlog=log.reshape((3,5))
flat= a.flatten()
print("\n 5*3 array:\n",a)
print("\n array all zeros:\n",az)
print("\n array with random numbers:\n",ar)
print("\n range values:\n",ae)
print("\n original array:\n",log)
print("\n reshaped array:\n",newlog)
print("\n flattered array:\n",flat)
print("\n no.of dimesnsions:\n",a.ndim)




 5*3 array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 array all zeros:
 [[0. 0.]
 [0. 0.]]

 array with random numbers:
 [[0.43833499 0.12145344 0.3104155 ]
 [0.8150255  0.71631097 0.37097467]
 [0.31778445 0.79479071 0.37916999]
 [0.73364383 0.81908654 0.02921199]
 [0.37887792 0.26746902 0.19013187]]

 range values:
 [0 1 2 3 4 5]

 original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 flattered array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 no.of dimesnsions:
 2


In [7]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
newtype= a.astype('f')
print("\n convert array element\n",newtype)
print("converted array ;",newtype.dtype)


 convert array element
 [[1. 2. 3.]
 [3. 4. 5.]]
converted array ; float32


In [3]:
import numpy as np
a=np.array([[1,2],[7,8]])
print("\n size of array:",a.size)


 size of array: 4
