In [4]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)

(array([1, 4], dtype=int64),)


In [10]:
import numpy as np
a=np.array([1,6,3,4,6,5])
x=np.where(a==6)
print(x)

(array([1, 4], dtype=int64),)


In [11]:
import numpy as np
b=np.array([0,1,2,3,4,5,6,7,8,9])
y=np.searchsorted(b,3,side='left')
print(y)

3


In [12]:
import numpy as np
b=np.array([0,1,2,3,7,8,9])
y=np.searchsorted(b,8,side='right')
print(y)

6


In [14]:
import numpy as n
b= np.array([9,5,12,7,6,4])
print(np.sort(b))

[ 4  5  6  7  9 12]


In [15]:
import numpy as np
d=np.array([[7,4,9],[9,1,4]])
print(np.sort(d))

[[4 7 9]
 [1 4 9]]


In [17]:
import numpy as np
x=np.array([31,78,69,88])
y=[False, True, False, True]
new=x[y]
print(y)
print(new)

[False, True, False, True]
[78 88]


In [18]:
import numpy as np
x=np.array([31,78,69,88])
filter=x<70
new=x[filter]
print(filter)
print(new)

[ True False  True False]
[31 69]
